#ifndef MASKS_H
#define MASKS_H

#define MOVEMENT_MASK (COMPONENT_POSITION | COMPONENT_VELOCITY)
#define RENDER_MASK (COMPONENT_RENDER)
#define PLAYER_MASK (COMPONENT_RENDER | COMPONENT_POSITION | COMPONENT_VELOCITY | COMPONENT_PHYSICS)

#endif